export {default as Blog} from "./blog/Blog"
export {default as Companylogo} from "./companylogo/Companylogo"
export {default as Cta} from "./cta/Cta"
export {default as Feature} from "./feature/Feature"
export {default as Features} from "./features/Features"
export {default as Footer} from "./footer/Footer"
export {default as Header} from "./header/Header"
export {default as Navbar} from "./navbar/Navbar"
export {default as Whatisgpt3} from "./what is gpt3/Whatisgpt3"